<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpDalTest.cs" />
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpRepoTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="WireMock.Net" Version="1.6.9" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bilreg.Api\Bilreg.Api.csproj" />
    <ProjectReference Include="..\Bilreg.Application\Bilreg.Application.csproj" />
    <ProjectReference Include="..\Bilreg.Domain\Bilreg.Domain.csproj" />
    <ProjectReference Include="..\Bilreg.Infrastructure\Bilreg.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AdmisiRanapContext\" />
    <Folder Include="AdmisiRanapContext\OpnameRequestFeature\" />
    <Folder Include="AdmisiRanapContext\ReservationFeature\" />
    <Folder Include="AdmisiRanapContext\AdmissionFeature\" />
    <Folder Include="AdmisiRanapContext\WaitingListFeature\" />
  </ItemGroup>

</Project>
