INSERT INTO ta_cara_masuk_dk (fs_kd_cara_masuk_dk, fs_nm_cara_masuk_dk)
SELECT '1', 'RUJUKAN RSU/RSK/RB' UNION
SELECT '2', 'RUJUKAN PUSKESMAS' UNION
SELECT '3', 'RUJUKAN DR/DRG' UNION
SELECT '4', 'RUJUKAN DR SPESIALIS' UNION
SELECT '5', 'RUJUKAN PARAMEDIK' UNION
SELECT '6', 'DUKUN TERLATIH' UNION
SELECT '7', 'KASUS POLISI' UNION
SELECT '8', 'DATANG SENDIRI' UNION
SELECT '9', 'KUNJUNGAN RUMAH';
