CREATE TABLE t_bp_piutang_hdr(
    fs_kd_piutang VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_piutang DEFAULT(''),
    fs_kd_jurnal_buat VARCHAR(20) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_jurnal_buat DEFAULT(''),
    fs_kd_rek VARCHAR(20) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_rek DEFAULT(''),
    fn_piutang DECIMAL(18,2) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_piutang DEFAULT(0),
    fn_sisa DECIMAL(18,2) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_sisa DEFAULT(0),
    fd_tgl_piutang VARCHAR(10)  NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_tgl_piutang DEFAULT('3000-01-01'),
    fd_jatuh_tempo VARCHAR(10)  NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_jatuh_tempo DEFAULT('3000-01-01'),
    fd_rencana_cair VARCHAR(10)  NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_rencana_cair DEFAULT('3000-01-01'),
    fs_kd_iii VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_iii DEFAULT(''),
    fs_kd_bu VARCHAR(8) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_bu DEFAULT(''),
    fs_departemen VARCHAR(40) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_departemen DEFAULT(''),
    fs_keterangan VARCHAR(200) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_keterangan DEFAULT(''),
    fs_keterangan_jb VARCHAR(200) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_keterangan_jb DEFAULT(''),
    fs_uraian VARCHAR(200) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_uraian DEFAULT(''),
    fs_kd_bp_piutang_tipe1 VARCHAR(3) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_bp_piutang_tipe1 DEFAULT(''),
    fs_kd_bp_piutang_tipe2 VARCHAR(3) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_bp_piutang_tipe2 DEFAULT(''),
    fd_tgl_void VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_tgl_void DEFAULT('3000-01-01'),
    fn_order_pelunasan DECIMAL(18,0) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_order_pelunasan DEFAULT(0),
    fs_kd_bart_aktif VARCHAR(35) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_bart_aktif DEFAULT(''),
    fs_kd_mr VARCHAR(15) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_mr DEFAULT(''),
    fs_kd_peg VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_peg DEFAULT(''),
    fs_no_peserta VARCHAR(30) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_no_peserta DEFAULT(''),
    fs_nm_peserta VARCHAR(40) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_nm_peserta DEFAULT(''),
    fs_kd_angsur_aktif VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fs_kd_angsur_aktif DEFAULT(''),
    fn_angsur DECIMAL(18,2) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_angsur DEFAULT(0),
    fd_tgl_kirim VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_tgl_kirim DEFAULT('3000-01-01'),
    fd_tgl_terima VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_tgl_terima DEFAULT('3000-01-01'),
    fn_nilai_jasa DECIMAL(18,2) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_nilai_jasa DEFAULT(0),
    fn_nilai_obat DECIMAL(18,2) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fn_nilai_obat DEFAULT(0),
    fd_tgl_tagih VARCHAR(10) NOT NULL CONSTRAINT DF_t_bp_piutang_hdr_fd_tgl_tagih DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_t_bp_piutang_hdr PRIMARY KEY CLUSTERED(fs_kd_piutang)
)
GO
