CREATE TABLE BILREG_PasienLog (
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILREG_PasienLog_PasienId DEFAULT(''),
    LogDate VARCHAR(30) NOT NULL CONSTRAINT DF_BILREG_PasienLog_LogDate DEFAULT (''),
    Activity VARCHAR(30) NOT NULL CONSTRAINT DF_BILREG_PasienLog_Activity DEFAULT (''),
    UserId VARCHAR(30) NOT NULL CONSTRAINT DF_BILREG_PasienLog_UserId DEFAULT (''),
    ChangeLog VARCHAR(MAX) NOT NULL CONSTRAINT DF_BILREG_PasienLog_ChangeLog DEFAULT (''),

    INDEX IX_BILREG_PasienLog_PasienID CLUSTERED (PasienId)
)