CREATE TABLE BILRG_IgdVisitEvent (
    IgdVisitId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_IgdVisitId DEFAULT(''),
    NoEvent INT NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_NoEvent DEFAULT(0),

    EventKind VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_EventKind DEFAULT(''),
    EventDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_EventDateTime DEFAULT('3000-01-01'),
    UserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_UserId DEFAULT(''),
    Notes VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_IgdVisitEvent_Notes DEFAULT(''),

    CONSTRAINT PK_BILRG_IgdVisitEvent PRIMARY KEY CLUSTERED (IgdVisitId, NoEvent)
);
GO
