CREATE TABLE BILRG_ScheduleOp
(
    ScheduleOpId    VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_ScheduleOpId DEFAULT(''),
    ScheduleOpDate  DATETIME NOT NULL CONSTRAINT DF_BILRG_SCheduleOp_ScheduleOpDate DEFAULT('3000-01-01'), 
    OrderOpId       VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_OrderOpId DEFAULT(''),
    PasienId        VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_PasienId DEFAULT(''),
    UrgencyLevel    INT NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_UrgencyLevel DEFAULT(0),
    Durasi          INT NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_Durasi DEFAULT(0),
    TglOp           DATETIME NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_TglOp DEFAULT('3000-01-01'),
    KamarId         VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_KamarId DEFAULT(''),
    RegId           VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_RegId DEFAULT(''),
    PpaId           VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_PpaId DEFAULT(''),

    CrtUser         VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_CrtUser DEFAULT(''),
    CrtDate         DATETIME NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_CrtDate DEFAULT('3000-01-01'),
    UpdUser         VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_UpdUser DEFAULT(''),
    UpdDate         DATETIME NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_UpdDate DEFAULT('3000-01-01'),
    VodUser         VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_VodUser DEFAULT(''),
    VodDate         DATETIME NOT NULL CONSTRAINT DF_BILRG_ScheduleOp_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_ScheduleOp PRIMARY KEY CLUSTERED(ScheduleOpId)
)
GO

CREATE INDEX IX_BILRG_ScheduleOp_OrderOpId
    ON BILRG_ScheduleOp (PasienId, OrderOpId, ScheduleOpId)
    WITH(FILLFACTOR=98)
GO
