CREATE TABLE TA_REG_JAMINAN(
    FS_KD_REG VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_FS_KD_REG DEFAULT(''),
    FS_KD_POLIS VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_FS_KD_POLIS DEFAULT(''),
    FS_KD_TRS_BL1 VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_FS_KD_TRS_BL1 DEFAULT(''),
    FS_NO_SKP VARCHAR (25) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_FS_NO_SKP DEFAULT(''),
    fs_kd_perusahaan VARCHAR (5) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_fs_kd_perusahaan DEFAULT(''),
    CRTTGL VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_CRTTGL DEFAULT(''),
    CRTJAM VARCHAR (8) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_CRTJAM DEFAULT(''),
    CRTIPA VARCHAR (40) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_CRTIPA DEFAULT(''),
    CRTVER VARCHAR (12) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_CRTVER DEFAULT(''),
    CRTUSR VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_CRTUSR DEFAULT(''),
    UPDTGL VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_UPDTGL DEFAULT(''),
    UPDJAM VARCHAR (8) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_UPDJAM DEFAULT(''),
    UPDIPA VARCHAR (40) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_UPDIPA DEFAULT(''),
    UPDVER VARCHAR (12) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_UPDVER DEFAULT(''),
    UPDUSR VARCHAR (10) NOT NULL CONSTRAINT DF_TA_REG_JAMINAN_UPDUSR DEFAULT(''),
    
    CONSTRAINT PK_TA_REG_JAMINAN PRIMARY KEY CLUSTERED (FS_KD_REG)
)

