CREATE TABLE BILRG_TindakanIgd (
    TindakanIgdId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_TindakanIgdId DEFAULT(''),
    IgdVisitId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_IgdVisitId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_RegId DEFAULT(''),
    ReffId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_ReffId DEFAULT(''),
    Descriptions VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_Description DEFAULT(''),
    Qty INT NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_Qty DEFAULT(0),
    Aktifitas INT NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_Aktifitas DEFAULT(0),
    PpaId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_PpaId DEFAULT(''),
    PpaName VARCHAR(45) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_PpaName DEFAULT(''),
    
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_CrtDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_TindakanIgd PRIMARY KEY CLUSTERED (TindakanIgdId)
);
GO

CREATE INDEX IX_BILRG_TindakanIgd_Visit ON BILRG_TindakanIgd(IgdVisitId);
GO
