CREATE TABLE BILRG_TindakanIgd (
    TindakanIgdId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_TindakanIgdId DEFAULT(''),
    IgdVisitId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_IgdVisitId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_RegId DEFAULT(''),
    TarifId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_TarifId DEFAULT(''),
    TarifName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_TarifName DEFAULT(''),
    Qty INT NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_Qty DEFAULT(0),
    Price DECIMAL(18, 2) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_Price DEFAULT(0),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_TindakanIgd_CrtDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_TindakanIgd PRIMARY KEY CLUSTERED (TindakanIgdId)
);
GO

CREATE INDEX IX_BILRG_TindakanIgd_Visit ON BILRG_TindakanIgd(IgdVisitId);
GO
