INSERT INTO ta_layanan_tipe_dk (fs_kd_layanan_tipe_dk, fs_nm_layanan_tipe_dk)
VALUES
('01','Penyakit Dalam'),
('02','Bedah'),
('03','Kesehatan  Anak'),
('04','Obstetrik & Ginekologi'),
('05','Ginekologi'),
('06','Bedah Syaraf (Lainnya)'),
('07','Syaraf (Lainnya)'),
('08','Jiwa'),
('09','THT'),
('10','Mata'),
('11','Kulit & Kelamin'),
('12','Gigi & Mulut'),
('13','Kardiovaskuler'),
('14','Radioterapi'),
('15','Bedah Orthopedi'),
('16','Paru - Paru'),
('17','Kusta'),
('18','Umum'),
('19','Unit Darurat'),
('20','Rehabilitas Medik'),
('21','Isolasi'),
('22','Luka Bakar'),
('23','ICU'),
('24','ICCU'),
('25','Keluarga Berencana'),
('26','Rawat Darurat'),
('27','Akupungtur Medik'),
('28','Konsultasi Gizi'),
('29','Day Care'),
('30','Lain - lain'),
('31','Psikotes'),
('32','Konsultasi'),
('33','Terap Medikamentosa'),
('34','Elektro Medik'),
('35','Psikoterapi'),
('36','Play Therapy'),
('37','Rehabilitasi Medik Psikiatrik'),
('38','Kunjungan Rumah'),
('39','Kesehatan Anak Neonatal'),
('40','Kesehatan Anak Non Neonatal'),
('41','Laboratorium'),
('42','Radiologi'),
('43','Pelayanan Gawat Darurat'),
('44','NICU / PICU'),
('45','Pentalaksana Pengguna NAPZA'),
('46','Kedokteran Nuklir'),
('47','Napza'),
('48','Obsgyn'),
('49','Urologi'),
('50','Bedah Anak'),
('51','Digestive'),
('52','Geriatri'),
('53','Psikologi'),
('54','Bedah Syaraf (Stroke)'),
('55','Syaraf (Stroke)'),
('56','Kanker'),
('57','Uronefrologi'),
('88','Perinatologi');