using Bilreg.Api.Authorization;
using Bilreg.Application.Shared;
using Bilreg.Application.Shared.User;
using Bilreg.Test.PaymentContext.TataRekeningFeature.Api;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Moq;

namespace Bilreg.Test.Authentication;

/// <summary>
/// Boots the real Bilreg.Api host with the production JWT Bearer pipeline intact
/// (issuer/audience/signing key/lifetime validation preserved). Only the external USMAN
/// identity provider and the persistence layer are mocked so a full
/// login -> token -> protected endpoint flow can run in-memory.
/// </summary>
public sealed class JwtAuthWebApplicationFactory : WebApplicationFactory<Program>
{
    public TataRekeningApiTestHarness Harness { get; } = new();
    public Mock<IUsmanGetUserService> UsmanGetUserService { get; } = new();

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Development");
        builder.ConfigureTestServices(services =>
        {
            // Mock persistence so a protected endpoint can return 200 without a database.
            Harness.ConfigureServices(services);

            // Keep the REAL claims-based user context so the actor id is read from the JWT,
            // not from a test double. This is what proves ICurrentUserContext is populated.
            services.RemoveAll<ICurrentUserContext>();
            services.AddScoped<ICurrentUserContext, HttpCurrentUserContext>();

            // Replace only the external USMAN call; JWT is still generated by Bilreg.Api itself.
            services.RemoveAll<IUsmanGetUserService>();
            services.AddScoped(_ => UsmanGetUserService.Object);
        });
    }
}
