CREATE TABLE tc_mr_ktp
(
    FS_KD_MR               VARCHAR(15) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KD_MR DEFAULT(''),
    FS_NIK                 VARCHAR(16) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_NIK DEFAULT(''),
    FS_NAMA_KTP            VARCHAR(50) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_NAMA_KTP DEFAULT(''),
    FS_ALM_KTP             VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_ALM_KTP DEFAULT(''),
    FS_RT_KTP              VARCHAR(3) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_RT_KTP DEFAULT(''),
    FS_RW_KTP              VARCHAR(3) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_RW_KTP DEFAULT(''),
    FS_KD_KELURAHAN_KTP    VARCHAR(13) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KD_KELURAHAN_KTP DEFAULT(''),
    FS_KELURAHAN_KTP       VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KELURAHAN_KTP DEFAULT(''),
    FS_KD_KECAMATAN_KTP    VARCHAR(7) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KD_KECAMATAN_KTP DEFAULT(''),
    FS_KECAMATAN_KTP       VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KECAMATAN_KTP DEFAULT(''),
    FS_KD_KABUPATEN_KTP    VARCHAR(4) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KD_KABUPATEN_KTP DEFAULT(''),
    FS_KABUPATEN_KTP       VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KABUPATEN_KTP DEFAULT(''),
    FS_KD_PROPINSI_KTP     VARCHAR(2) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_KD_PROPINSI_KTP DEFAULT(''),
    FS_PROPINSI_KTP        VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_PROPINSI_KTP DEFAULT(''),
    FS_TEMPAT_LAHIR        VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_TEMPAT_LAHIR DEFAULT(''),
    FS_SEX                 VARCHAR(1) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_SEX DEFAULT(''),
    FD_TGL_LAHIR           VARCHAR(10) NOT NULL CONSTRAINT DF_tc_mr_ktp_FD_TGL_LAHIR DEFAULT(''),
    FS_GOL_DARAH           VARCHAR(2) NOT NULL CONSTRAINT DF_tc_mr_ktp_FS_GOL_DARAH DEFAULT(''),

    CONSTRAINT PK_tc_mr_ktp PRIMARY KEY CLUSTERED(FS_KD_MR)
)