INSERT INTO ta_pendidikan_dk 
SELECT '1','TIDAK SEKOLAH' UNION
SELECT '2','BELUM/TIDAK TAMAT SD' UNION
SELECT '3','SD' UNION
SELECT '4','SMP' UNION
SELECT '5','SMA' UNION
SELECT '6','DIPLOMA' UNION
SELECT '7','SARJANA'