CREATE TABLE tc_mr_id
(
    fs_mr         VARCHAR(15) NOT NULL CONSTRAINT DF_tc_mr_id_fs_mr DEFAULT(''),
    JenisID       VARCHAR(6) NOT NULL CONSTRAINT DF_tc_mr_id_JenisID DEFAULT(''),
    NoID          VARCHAR(30) NOT NULL CONSTRAINT DF_tc_mr_id_NoID DEFAULT(''),
    CRTTGL        VARCHAR(10) NOT NULL CONSTRAINT DF_tc_mr_id_CRTTGL DEFAULT('3000-01-01'),
    CRTJAM        VARCHAR(8) NOT NULL CONSTRAINT DF_tc_mr_id_CRTJAM DEFAULT('00:00:00'),
    CRTIPA        VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_id_CRTIPA DEFAULT(''),
    CRTVER        VARCHAR(12) NOT NULL CONSTRAINT DF_tc_mr_id_CRTVER DEFAULT(''),
    CRTUSR        VARCHAR(10) NOT NULL CONSTRAINT DF_tc_mr_id_CRTUSR DEFAULT(''),
    UPDTGL        VARCHAR(10) NOT NULL CONSTRAINT DF_tc_mr_id_UPDTGL DEFAULT('3000-01-01'),
    UPDJAM        VARCHAR(8) NOT NULL CONSTRAINT DF_tc_mr_id_UPDJAM DEFAULT('00:00:00'),
    UPDIPA        VARCHAR(40) NOT NULL CONSTRAINT DF_tc_mr_id_UPDIPA DEFAULT(''),
    UPDVER        VARCHAR(12) NOT NULL CONSTRAINT DF_tc_mr_id_UPDVER DEFAULT(''),
    UPDUSR        VARCHAR(10) NOT NULL CONSTRAINT DF_tc_mr_id_UPDUSR DEFAULT(''),
    fi_imageID    IMAGE,
    fs_rfid       VARCHAR(20) NOT NULL CONSTRAINT DF_tc_mr_id_fs_rfid DEFAULT(''),

    CONSTRAINT PK_tc_mr_id PRIMARY KEY CLUSTERED(fs_mr, JenisID)
)