CREATE TABLE BILRG_AptInvoiceItem (
    InvoiceId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_InvoiceId DEFAULT(''),
    ItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_ItemNo DEFAULT(0),
    SalesOrderItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_SalesOrderItemNo DEFAULT(0),
    BrgId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_BrgId DEFAULT(''),
    BrgName VARCHAR(80) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_BrgName DEFAULT(''),
    ItemKind INT NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_ItemKind DEFAULT(0),
    Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_Qty DEFAULT(0),
    HargaSatuan DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_HargaSatuan DEFAULT(0),
    Diskon DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_Diskon DEFAULT(0),
    Biaya DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_Biaya DEFAULT(0),
    Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_Tax DEFAULT(0),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptInvoiceItem_Total DEFAULT(0),
    CONSTRAINT PK_BILRG_AptInvoiceItem PRIMARY KEY CLUSTERED (InvoiceId, ItemNo)
);
GO
