CREATE TABLE BILRG_AptQueueClose (
    QueueCloseId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_QueueCloseId DEFAULT(''),
    AntrianId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_AntrianId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_NoUrut DEFAULT(0),
    Reason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_Reason DEFAULT(''),
    StaffId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_StaffId DEFAULT(''),
    EffectiveAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_EffectiveAt DEFAULT('3000-01-01'),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptQueueClose_VodDate DEFAULT('3000-01-01'),
    CONSTRAINT PK_BILRG_AptQueueClose PRIMARY KEY CLUSTERED (QueueCloseId)
);
GO
CREATE UNIQUE INDEX UX_BILRG_AptQueueClose_Queue ON BILRG_AptQueueClose(AntrianId, NoUrut);
GO
