CREATE TABLE BILRG_AptCopyResep (
    CopyResepId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_CopyResepId DEFAULT(''),
    ResepKerjaId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_ResepKerjaId DEFAULT(''),
    SalesOrderId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_SalesOrderId DEFAULT(''),
    Reason INT NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_Reason DEFAULT(0),
    IssuedBy VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_IssuedBy DEFAULT(''),
    IssuedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_IssuedAt DEFAULT('3000-01-01'),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptCopyResep_VodDate DEFAULT('3000-01-01'),
    CONSTRAINT PK_BILRG_AptCopyResep PRIMARY KEY CLUSTERED (CopyResepId)
);
GO
