CREATE TABLE BILRG_AptResepKerjaItem (
    ResepKerjaId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_ResepKerjaId DEFAULT(''),
    ItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_ItemNo DEFAULT(0),
    SourceItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_SourceItemNo DEFAULT(0),
    BrgId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_BrgId DEFAULT(''),
    BrgName VARCHAR(80) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_BrgName DEFAULT(''),
    SatuanId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_SatuanId DEFAULT(''),
    SatuanName VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_SatuanName DEFAULT(''),
    Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_Qty DEFAULT(0),
    Iter INT NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_Iter DEFAULT(0),
    Signa VARCHAR(80) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_Signa DEFAULT(''),
    Instruction VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_Instruction DEFAULT(''),
    Note VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_Note DEFAULT(''),
    IsRacik BIT NOT NULL CONSTRAINT DF_BILRG_AptResepKerjaItem_IsRacik DEFAULT(0),
    CONSTRAINT PK_BILRG_AptResepKerjaItem PRIMARY KEY CLUSTERED (ResepKerjaId, ItemNo)
);
GO
