CREATE TABLE BILRG_AptTelaahResep (
    TelaahResepId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_TelaahResepId DEFAULT(''),
    ResepKerjaId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_ResepKerjaId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_RegId DEFAULT(''),
    TelaahStatus INT NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_TelaahStatus DEFAULT(0),
    PharmacistId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_PharmacistId DEFAULT(''),
    StartedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_StartedAt DEFAULT('3000-01-01'),
    CompletedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_CompletedAt DEFAULT('3000-01-01'),
    Version INT NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_Version DEFAULT(1),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptTelaahResep_VodDate DEFAULT('3000-01-01'),
    CONSTRAINT PK_BILRG_AptTelaahResep PRIMARY KEY CLUSTERED (TelaahResepId)
);
GO
CREATE UNIQUE INDEX UX_BILRG_AptTelaahResep_ResepKerja ON BILRG_AptTelaahResep(ResepKerjaId) WHERE VodDate = '3000-01-01';
GO
