CREATE TABLE BILRG_AptJualBebas (
    JualBebasId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_JualBebasId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_RegId DEFAULT(''),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_PasienId DEFAULT(''),
    PasienName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_PasienName DEFAULT(''),
    AcceptedBy VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_AcceptedBy DEFAULT(''),
    AcceptedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_AcceptedAt DEFAULT('3000-01-01'),
    RequestStatus INT NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_RequestStatus DEFAULT(0),
    Version INT NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_Version DEFAULT(1),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptJualBebas_VodDate DEFAULT('3000-01-01'),
    CONSTRAINT PK_BILRG_AptJualBebas PRIMARY KEY CLUSTERED (JualBebasId)
);
GO
