CREATE TABLE BILRG_AptCopyResepItem (
    CopyResepId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_CopyResepId DEFAULT(''),
    ItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_ItemNo DEFAULT(0),
    ResepKerjaItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_ResepKerjaItemNo DEFAULT(0),
    BrgId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_BrgId DEFAULT(''),
    Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_Qty DEFAULT(0),
    Note VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptCopyResepItem_Note DEFAULT(''),
    CONSTRAINT PK_BILRG_AptCopyResepItem PRIMARY KEY CLUSTERED (CopyResepId, ItemNo)
);
GO
