CREATE TABLE BILRG_AptDispensing (
    DispensingId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_DispensingId DEFAULT(''),
    SalesOrderId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_SalesOrderId DEFAULT(''),
    CareSetting INT NOT NULL CONSTRAINT DF_BILRG_AptDispensing_CareSetting DEFAULT(0),
    DispensingStatus INT NOT NULL CONSTRAINT DF_BILRG_AptDispensing_DispensingStatus DEFAULT(0),
    PharmacyUnitLayananId VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_PharmacyUnitLayananId DEFAULT(''),
    TemporaryUnitLayananId VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_TemporaryUnitLayananId DEFAULT(''),
    ReleasedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_ReleasedAt DEFAULT('3000-01-01'),
    PreparationStartedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_PreparationStartedAt DEFAULT('3000-01-01'),
    PreparedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_PreparedAt DEFAULT('3000-01-01'),
    EducationAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_EducationAt DEFAULT('3000-01-01'),
    EducationPharmacistId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_EducationPharmacistId DEFAULT(''),
    EducationNote VARCHAR(512) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_EducationNote DEFAULT(''),
    OverrideAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_OverrideAt DEFAULT('3000-01-01'),
    OverridePharmacistId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_OverridePharmacistId DEFAULT(''),
    OverrideReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_OverrideReason DEFAULT(''),
    HandoverAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_HandoverAt DEFAULT('3000-01-01'),
    RecipientPhone VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_RecipientPhone DEFAULT(''),
    RecipientRelationship VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_RecipientRelationship DEFAULT(''),
    CancelledAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_CancelledAt DEFAULT('3000-01-01'),
    ExpiredAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_ExpiredAt DEFAULT('3000-01-01'),
    CancelReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_CancelReason DEFAULT(''),
    PickupCalledAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_PickupCalledAt DEFAULT('3000-01-01'),
    Version INT NOT NULL CONSTRAINT DF_BILRG_AptDispensing_Version DEFAULT(1),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_AptDispensing_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_AptDispensing_VodDate DEFAULT('3000-01-01'),
    CONSTRAINT PK_BILRG_AptDispensing PRIMARY KEY CLUSTERED (DispensingId)
);
GO
