CREATE TABLE BILRG_AptJualBebasItem (
    JualBebasId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_JualBebasId DEFAULT(''),
    ItemNo INT NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_ItemNo DEFAULT(0),
    BrgId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_BrgId DEFAULT(''),
    BrgName VARCHAR(80) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_BrgName DEFAULT(''),
    SatuanId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_SatuanId DEFAULT(''),
    Qty DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_Qty DEFAULT(0),
    Signa VARCHAR(80) NOT NULL CONSTRAINT DF_BILRG_AptJualBebasItem_Signa DEFAULT(''),
    CONSTRAINT PK_BILRG_AptJualBebasItem PRIMARY KEY CLUSTERED (JualBebasId, ItemNo)
);
GO
