@Bilreg.Api_HostAddress = http://localhost:5189

POST {{Bilreg.Api_HostAddress}}/api/GrupKomponen
Content-Type: application/json
Accept: application/json

{
  "GrupKomponenId": "01",
  "GrupKomponenName": "Jasa Medis"
}

