@Bilreg.Api_HostAddress = http://localhost:5189

POST {{Bilreg.Api_HostAddress}}/api/Kelas
Content-Type: application/json
Accept: application/json

{
  "kelasId": "102",
  "kelasName": "Kelas Olahraga"
}

