INSERT INTO ta_agama
SELECT '1',	'ISLAM' UNION
SELECT '2',	'KRISTEN' UNION
SELECT '3',	'KATOLIK' UNION
SELECT '4',	'HINDU' UNION
SELECT '5',	'BUDHA' UNION
SELECT '6',	'KONGHUCU' UNION
SELECT '7',	'KEPERCAYAAN'