INSERT INTO ta_pekerjaan_dk (fs_kd_pekerjaan_dk, fs_nm_pekerjaan_dk)
SELECT '001','PNS' UNION
SELECT '002','TNI/POLRI' UNION
SELECT '003','PENSIUNAN' UNION
SELECT '004','SWASTA' UNION
SELECT '005','PEDAGANG' UNION
SELECT '006','NELAYAN' UNION
SELECT '007','PETANI' UNION
SELECT '008','PEKERJA LEPAS' UNION
SELECT '009','IBU RUMAH TANGGA' UNION
SELECT '010','PELAJAR' UNION
SELECT '011','MAHASISWA' UNION
SELECT '012','DI BAWAH UMUR' UNION
SELECT '013','TIDAK BEKERJA' UNION
SELECT '014','TIDAK TAHU' UNION
SELECT '015','WIRASWASTA' UNION
SELECT 'XXX','PEKERJAAN'
