CREATE TABLE BILRG_Booking(
    BookingId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_Booking_BookingId DEFAULT(''),
    BookingDate DATETIME NOT NULL CONSTRAINT DF_BILRG_Booking_BookingDate DEFAULT('3000-01-01'),
    
    PasienName VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_Booking_PasienName DEFAULT(''),
    TglLahir DATETIME NOT NULL CONSTRAINT DF_BILRG_Booking_TglLahir DEFAULT('3000-01-01'),
    Gender VARCHAR(1) NOT NULL CONSTRAINT DF_BILRG_Booking_Gender DEFAULT(0),
    Alamat VARCHAR(100) NOT NULL CONSTRAINT DF_BILRG_Booking_Alamat DEFAULT(''),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_Booking_PasienId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_Booking_RegId DEFAULT(''),
    
    TglBerobat DATETIME NOT NULL CONSTRAINT DF_BILRG_TglBerobat DEFAULT('3000-01-01'),
    JamPraktek VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_JamPraktek DEFAULT('00:00'),
    LayananId VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_Booking_LayananId DEFAULT(''),
    DokterId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_Booking_DokterId DEFAULT(''),
    NoAntrian INT NOT NULL CONSTRAINT DF_BILRG_Booking_NoAntrian DEFAULT(0),
    
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_Booking_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_Booking_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_Booking_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_Booking_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_Booking_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_Booking_VodDate DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_BILRG_Booking PRIMARY KEY CLUSTERED (BookingId)
)