CREATE TABLE BILRG_BedIgd (
    BedIgdId VARCHAR(8) NOT NULL CONSTRAINT DF_BILRG_BedIgd_BedIgdId DEFAULT(''),
    BedIgdName VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_BedIgd_BedIgdName DEFAULT(''),
    KamarName VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_BedIgd_KamarName DEFAULT(''),

    BedState VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_BedIgd_BedState DEFAULT('ACTIVE'),
    CurrentIgdVisitId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_BedIgd_CurrentIgdVisitId DEFAULT(''),

    OccupyUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_BedIgd_OccupyUser DEFAULT(''),
    OccupyDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_BedIgd_OccupyDateTime DEFAULT('3000-01-01'),

    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_BedIgd_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_BedIgd_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_BedIgd_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_BedIgd_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_BedIgd_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_BedIgd_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_BedIgd PRIMARY KEY CLUSTERED (BedIgdId)
);
GO

CREATE INDEX IX_BILRG_BedIgd_State ON BILRG_BedIgd(BedState);
GO

CREATE UNIQUE INDEX UQ_BILRG_BedIgd_VisitActive
    ON BILRG_BedIgd(CurrentIgdVisitId)
    WHERE BedState = 'OCCUPIED' AND CurrentIgdVisitId <> '';
GO
