CREATE TABLE BILRG_PakaiBed (
    PakaiBedId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_PakaiBedId DEFAULT(''),

    IgdVisitId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_IgdVisitId DEFAULT(''),
    BedIgdId VARCHAR(8) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_BedIgdId DEFAULT(''),
    BedIgdName VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_BedIgdName DEFAULT(''),

    CheckInDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_PakaiBed_CheckInDateTime DEFAULT('3000-01-01'),
    CheckInUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_CheckInUserId DEFAULT(''),
    CheckOutDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_PakaiBed_CheckOutDateTime DEFAULT('3000-01-01'),
    CheckOutUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_PakaiBed_CheckOutUserId DEFAULT(''),

    CONSTRAINT PK_BILRG_PakaiBed PRIMARY KEY CLUSTERED (PakaiBedId)
);
GO

CREATE INDEX IX_BILRG_PakaiBed_Visit ON BILRG_PakaiBed(IgdVisitId);
GO
CREATE INDEX IX_BILRG_PakaiBed_BedOpen ON BILRG_PakaiBed(BedIgdId, CheckOutDateTime);
GO
