CREATE TABLE BILRG_BhpIgd (
    BhpIgdId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_BhpIgdId DEFAULT(''),
    IgdVisitId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_IgdVisitId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_RegId DEFAULT(''),
    BhpItemId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_BhpItemId DEFAULT(''),
    BhpItemName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_BhpItemName DEFAULT(''),
    Qty INT NOT NULL CONSTRAINT DF_BILRG_BhpIgd_Qty DEFAULT(0),
    Price DECIMAL(18, 2) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_Price DEFAULT(0),
    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_BhpIgd_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_BhpIgd_CrtDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_BhpIgd PRIMARY KEY CLUSTERED (BhpIgdId)
);
GO

CREATE INDEX IX_BILRG_BhpIgd_Visit ON BILRG_BhpIgd(IgdVisitId);
GO
