CREATE TABLE ta_trs_kartu_periksa
(
    fs_kd_trs              VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_trs DEFAULT(''),
    fd_tgl_trs             VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fd_tgl_trs DEFAULT(''),
    fs_jam_trs             VARCHAR(8) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_jam_trs DEFAULT(''),
    fs_kd_petugas          VARCHAR(50) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_petugas DEFAULT(''),
    fs_kd_reg              VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_reg DEFAULT(''),
    fs_kd_layanan          VARCHAR(5) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_layanan DEFAULT(''),
    fd_tgl_void            VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fd_tgl_void DEFAULT(''),
    fs_jam_void            VARCHAR(8) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_jam_void DEFAULT(''),
    fs_kd_petugas_void     VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_petugas_void DEFAULT(''),
    fs_kd_petugas_medis    VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_petugas_medis DEFAULT(''),
    fn_tinggi_badan        DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_tinggi_badan DEFAULT(0),
    fn_berat_badan         DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_berat_badan DEFAULT(0),
    fn_lpb                 DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_lpb DEFAULT(0),
    fs_advice              VARCHAR(512) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_advice DEFAULT(''),
    fn_sub_total           DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_sub_total DEFAULT(0),
    fn_total               DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_total DEFAULT(0),
    fb_resep               BIT NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fb_resep DEFAULT(0),
    fs_kd_medis_resep      VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_medis_resep DEFAULT(''),
    fs_kd_tipe_barang      VARCHAR(2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_tipe_barang DEFAULT(''),
    fn_iter_resep          DECIMAL(18,2) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fn_iter_resep DEFAULT(0),
    fs_kd_urgenitas        VARCHAR(1) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_fs_kd_urgenitas DEFAULT(''),
    CRTTGL                 VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_CRTTGL DEFAULT(''),
    CRTJAM                 VARCHAR(8) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_CRTJAM DEFAULT(''),
    CRTIPA                 VARCHAR(40) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_CRTIPA DEFAULT(''),
    CRTVER                 VARCHAR(12) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_CRTVER DEFAULT(''),
    CRTUSR                 VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_CRTUSR DEFAULT(''),
    UPDTGL                 VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_UPDTGL DEFAULT(''),
    UPDJAM                 VARCHAR(8) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_UPDJAM DEFAULT(''),
    UPDIPA                 VARCHAR(40) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_UPDIPA DEFAULT(''),
    UPDVER                 VARCHAR(12) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_UPDVER DEFAULT(''),
    UPDUSR                 VARCHAR(10) NOT NULL CONSTRAINT DF_ta_trs_kartu_periksa_UPDUSR DEFAULT(''),

    CONSTRAINT PK_ta_trs_kartu_periksa PRIMARY KEY CLUSTERED(fs_kd_trs)
)