CREATE TABLE tb_trs_dobill_umum2
(
    fs_kd_trs                 VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_trs DEFAULT(''),
    fs_kd_trs2                VARCHAR(13) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_trs2 DEFAULT(''),
    fn_no_urut                DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_no_urut DEFAULT(0),
    fb_void                   BIT NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fb_void DEFAULT(0),
    fs_kd_barang              VARCHAR(13) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_barang DEFAULT(''),
    fs_nm_barang              VARCHAR(50) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_nm_barang DEFAULT(''),
    fs_kd_tipe_barang         VARCHAR(2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_tipe_barang DEFAULT(''),
    fb_racik                  BIT NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fb_racik DEFAULT(0),
    fb_komponen               BIT NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fb_komponen DEFAULT(0),
    fs_kd_racik               VARCHAR(13) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_racik DEFAULT(''),
    fn_qty_racik              DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_qty_racik DEFAULT(0),
    fs_racik_qty              VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_racik_qty DEFAULT(''),
    fn_qty_barang             DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_qty_barang DEFAULT(0),
    fs_nm_satuan              VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_nm_satuan DEFAULT(''),
    fn_harga_satuan           DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_harga_satuan DEFAULT(0),
    fn_diskon                 DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_diskon DEFAULT(0),
    fn_biaya                  DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_biaya DEFAULT(0),
    fn_sub_total              DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_sub_total DEFAULT(0),
    fn_tax_prosen             DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_tax_prosen DEFAULT(0),
    fn_tax_rupiah             DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_tax_rupiah DEFAULT(0),
    fn_biaya_fee              DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_biaya_fee DEFAULT(0),
    fn_total                  DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_total DEFAULT(0),
    fs_etiket                 VARCHAR(64) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket DEFAULT(''),
    fs_kd_tipe_jaminan        VARCHAR(5) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_tipe_jaminan DEFAULT(''),
    fn_bulat                  DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_bulat DEFAULT(0),
    fs_kd_satuan              VARCHAR(3) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_kd_satuan DEFAULT(''),
    fn_etiket_qty             DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_etiket_qty DEFAULT(0),
    fs_etiket_qty             VARCHAR(3) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_qty DEFAULT(''),
    fn_etiket_hari            DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_etiket_hari DEFAULT(0),
    fs_etiket_kd_pakai        VARCHAR(3) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_kd_pakai DEFAULT(''),
    fs_etiket_catatan         VARCHAR(70) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_catatan DEFAULT(''),
    fs_etiket_jenis_obat      VARCHAR(1) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_jenis_obat DEFAULT(''),
    fs_etiket_kd_satuan_pakai VARCHAR(3) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_kd_satuan_pakai DEFAULT(''),
    fd_etiket_cetak           VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fd_etiket_cetak DEFAULT(''),
    fb_belibebas              BIT NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fb_belibebas DEFAULT(0),
    fs_etiket_hari            VARCHAR(5) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_etiket_hari DEFAULT(''),
    fb_paket_tarif            BIT NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fb_paket_tarif DEFAULT(0),
    fn_nilai_klaim            DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_nilai_klaim DEFAULT(0),
    fs_waktu_odd              VARCHAR(30) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fs_waktu_odd DEFAULT(''),
    fn_etiket_cetak           DECIMAL(18,2) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_fn_etiket_cetak DEFAULT(0),
    CRTTGL                    VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_CRTTGL DEFAULT(''),
    CRTJAM                    VARCHAR(8) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_CRTJAM DEFAULT(''),
    CRTIPA                    VARCHAR(40) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_CRTIPA DEFAULT(''),
    CRTVER                    VARCHAR(12) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_CRTVER DEFAULT(''),
    CRTUSR                    VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_CRTUSR DEFAULT(''),
    UPDTGL                    VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_UPDTGL DEFAULT(''),
    UPDJAM                    VARCHAR(8) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_UPDJAM DEFAULT(''),
    UPDIPA                    VARCHAR(40) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_UPDIPA DEFAULT(''),
    UPDVER                    VARCHAR(12) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_UPDVER DEFAULT(''),
    UPDUSR                    VARCHAR(10) NOT NULL CONSTRAINT DF_tb_trs_dobill_umum2_UPDUSR DEFAULT(''),

    CONSTRAINT PK_tb_trs_dobill_umum2 PRIMARY KEY CLUSTERED(fs_kd_trs, fs_kd_trs2)
)