CREATE TABLE BILRG_NilaiTarif
(
    NilaiTarifId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif DEFAULT(''),
    TarifId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif DEFAULT(''),
    KelasId VARCHAR(3) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif DEFAULT(''),
    TipeTarifId VARCHAR(2) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif DEFAULT(''),
    Nilai DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif DEFAULT(0),
    
    CONSTRAINT PK_BILRG_NilaiTarif PRIMARY KEY (NilaiTarifId)
)
GO
