CREATE TABLE BILRG_NilaiTarif
(
    NilaiTarifId VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif_NilaiTarifId DEFAULT(''),
    TarifId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif_TarifId DEFAULT(''),
    KelasId VARCHAR(3) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif_KelasId DEFAULT(''),
    TipeTarifId VARCHAR(2) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif_TipeTarifId DEFAULT(''),
    Nilai DECIMAL(18,2) NOT NULL CONSTRAINT DF_BILRG_NilaiTarif_Nilai DEFAULT(0),
    
    CONSTRAINT PK_BILRG_NilaiTarif PRIMARY KEY (NilaiTarifId)
)
GO
