CREATE TABLE BILRG_DischargeOp
(
    DischargeOpId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_DischargeOpId DEFAULT(''),
    DischargeOpDate DATETIME NOT NULL CONSTRAINT DF_BILRG_DischargeOp_DischargeOpDate DEFAULT('3000-01-01'),
    OrderOpId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_OrderOpId DEFAULT(''),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_PasienId DEFAULT(''),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_RegId DEFAULT(''),
    KamarId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_KamarId DEFAULT(''),
    PpaId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_PpaId DEFAULT(''),
    PatientCondition INT NOT NULL CONSTRAINT DF_BILRG_DischargeOp_PatientCondition DEFAULT(0),
    PostOpNote VARCHAR(1028) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_PostOpNote DEFAULT(''),

    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_DischargeOp_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_DischargeOp_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_DischargeOp_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_DischargeOp_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_DischargeOp PRIMARY KEY CLUSTERED(DischargeOpId)
)
GO