CREATE TABLE BILRG_OpCaseAktif(
    OrderOpId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OpCaseAktif_OrderOpId DEFAULT(''),
    OrderOpDate DATETIME NOT NULL CONSTRAINT DF_BILRG_OpCaseAktif_OrderOpDate DEFAULT('3000-01-01'),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_OpCaseAktif_PasienId DEFAULT(''),
    OpCaseState INT NOT NULL CONSTRAINT DF_BILRG_OpCaseAktif_OpCaseState DEFAULT(0),
    
    CONSTRAINT PK_BILRG_OpCaseAktif PRIMARY KEY CLUSTERED(OrderOpId)
)