CREATE TABLE BILRG_StartOp
(
    StartOpId    VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_StartOp_StartOpId    DEFAULT(''),
    StartOpTime  DATETIME    NOT NULL CONSTRAINT DF_BILRG_StartOp_StartOpTime  DEFAULT('3000-01-01 00:00:00'),
    OrderOpId    VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_StartOp_OrderOpId    DEFAULT(''),
    ScheduleOpId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_StartOp_ScheduleOpId DEFAULT(''),
    RegId        VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_StartOp_RegId        DEFAULT(''),
    PasienId     VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_StartOp_PasienId     DEFAULT(''),
    KamarOpId    VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_StartOp_KamarOpId    DEFAULT(''),
    PpaId        VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_StartOp_PpaId        DEFAULT(''),

    CrtUser      VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_StartOp_CrtUser DEFAULT(''),
    CrtDate      DATETIME    NOT NULL CONSTRAINT DF_BILRG_StartOp_CrtDate DEFAULT('3000-01-01'),
    UpdUser      VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_StartOp_UpdUser DEFAULT(''),
    UpdDate      DATETIME    NOT NULL CONSTRAINT DF_BILRG_StartOp_UpdDate DEFAULT('3000-01-01'),
    VodUser      VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_StartOp_VodUser DEFAULT(''),
    VodDate      DATETIME    NOT NULL CONSTRAINT DF_BILRG_StartOp_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_StartOp PRIMARY KEY CLUSTERED(StartOpId)
)
