CREATE TABLE BILRG_OpCase
(
    OrderOpId      VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OpCase_OrderOpId DEFAULT(''),
    OrderDate      DATETIME NOT NULL CONSTRAINT DF_BILRG_OpCase_OrderDate DEFAULT('3000-01-01'),
    NamaOperasi    VARCHAR(128) NOT NULL CONSTRAINT DF_BILRG_OpCase_NamaOperasi DEFAULT(''),
    PasienId       VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_OpCase_PasienId DEFAULT(''),
    RegId          VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OpCase_RegId DEFAULT(''),
    ScheduleOpId   VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OpCase_ScheduleOpId DEFAULT(''),
    ScheduledDate  DATETIME NOT NULL CONSTRAINT DF_BILRG_OpCase_ScheduledDate DEFAULT('3000-01-01'),
    DischargeOpId  VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OpCase_DischargeOpId DEFAULT(''),
    DischargedDate DATETIME NOT NULL CONSTRAINT DF_BILRG_OpCase_DischargedDate DEFAULT('3000-01-01'),
    OrderOpState   INT NOT NULL CONSTRAINT DF_BILRG_OpCase_OrderOpState DEFAULT(0),
    
    CONSTRAINT PK_BILRG_OpCase PRIMARY KEY (OrderOpId)
)