CREATE TABLE BILRG_OpCasePpa
(
    OrderOpId    VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OpCasePpa_OrderOpId DEFAULT(''),
    NoUrut       INT NOT NULL CONSTRAINT DF_BILRG_OpCasePpa_NoUrut DEFAULT(0),
    PpaId        VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OpCasePpa_PpaId DEFAULT(''),
    Role         VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_OpCasePpa_Role DEFAULT(''),
    AssignDate   DATETIME NOT NULL CONSTRAINT DF_BILRG_OpCasePpa_AssignDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_OpCasePpa PRIMARY KEY CLUSTERED(OrderOpId, NoUrut)
)
GO
