CREATE TABLE BILRG_PakaiBedIgd (
    PakaiBedIgdId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_PakaiBedIgdId DEFAULT(''),

    IgdVisitId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_IgdVisitId DEFAULT(''),
    BedIgdId VARCHAR(8) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_BedIgdId DEFAULT(''),
    BedIgdName VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_BedIgdName DEFAULT(''),

    CheckInDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_CheckInDateTime DEFAULT('3000-01-01'),
    CheckInUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_CheckInUserId DEFAULT(''),
    CheckOutDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_CheckOutDateTime DEFAULT('3000-01-01'),
    CheckOutUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_PakaiBedIgd_CheckOutUserId DEFAULT(''),

    CONSTRAINT PK_BILRG_PakaiBedIgd PRIMARY KEY CLUSTERED (PakaiBedIgdId)
);
GO

CREATE INDEX IX_BILRG_PakaiBedIgd_Visit ON BILRG_PakaiBedIgd(IgdVisitId);
GO
CREATE INDEX IX_BILRG_PakaiBedIgd_BedOpen ON BILRG_PakaiBedIgd(BedIgdId, CheckOutDateTime);
GO
