CREATE TABLE BILRG_OrderTdk (
    OrderTdkId        VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_OrderTdkId DEFAULT(''),
    OrderTdkDate      DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderTdk_OrderTdkDate DEFAULT('3000-01-01'),
    
    PasienId       VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_PasienId DEFAULT(''),
    PasienName     VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_PasienName DEFAULT(''),
    RegId          VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_RegId DEFAULT(''),

    PpaId          VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_PpaId DEFAULT(''),
    PpaName        VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_PpaName DEFAULT(''),
    LayananId      VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_LayananId DEFAULT(''),
    LayananName    VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_LayananName DEFAULT(''),

    TarifId        VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_TarifId DEFAULT(''),
    TarifName      VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_TarifName DEFAULT(''),
    FreeTextOrder  VARCHAR(128) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_FreeTextOrder DEFAULT(''),

    StatusOrder    INT NOT NULL CONSTRAINT DF_BILRG_OrderTdk_StatusOrder DEFAULT(0),

    CrtUser        VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_CrtUser DEFAULT(''),
    CrtDate        DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderTdk_CrtDate DEFAULT('3000-01-01'),
    UpdUser        VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_UpdUser DEFAULT(''),
    UpdDate        DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderTdk_UpdDate DEFAULT('3000-01-01'),
    VodUser        VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderTdk_VodUser DEFAULT(''),
    VodDate        DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderTdk_VodDate DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_BILRG_OrderTdk PRIMARY KEY CLUSTERED (OrderTdkId)
);