CREATE TABLE BILRG_OrderOp
(
    OrderOpId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_OrderOp_OrderOpId DEFAULT(''),
    OrderDate DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderOp_OrderDate DEFAULT('3000-01-01'),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_OrderOp_PasienId DEFAULT(''),
    NamaOperasi VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderOp_NamaOperasi DEFAULT(''),

    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OrderOp_RegId DEFAULT(''),
    Icd10Id VARCHAR(5) NOT NULL CONSTRAINT DF_BILRG_OrderOp_Icd10Id DEFAULT(''),
    JenisOperasiId VARCHAR(2) NOT NULL CONSTRAINT DF_BILRG_OrderOp_JenisOperasiId DEFAULT(''),
    UrgencyLevel INT NOT NULL CONSTRAINT DF_BILRG_OrderOp_UrgencyLevel DEFAULT(0),

    DokterId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_OrderOp_DokterId DEFAULT(''),
    EstimasiDurasi INT NOT NULL CONSTRAINT DF_BILRG_OrderOp_EstimasiDurasi DEFAULT(0),
    PreferedDate DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderOp_PreferedDate DEFAULT('3000-01-01'),
    SpecialEquipment VARCHAR(255) NOT NULL CONSTRAINT DF_BILRG_OrderOp_SpecialEquipment DEFAULT(''),

    CreateUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderOp_CreateUserId DEFAULT(''),
    CreateTimestamp DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderOp_CreateTimestamp DEFAULT('3000-01-01'),
    UpdateUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderOp_UpdateUserId DEFAULT(''),
    UpdateTimestamp DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderOp_UpdateTimestamp DEFAULT('3000-01-01'),
    VoidUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_OrderOp_VoidUserId DEFAULT(''),
    VoidTimestamp DATETIME NOT NULL CONSTRAINT DF_BILRG_OrderOp_VoidTimestamp DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_OrderOp PRIMARY KEY CLUSTERED(OrderOpId)
)
GO

CREATE INDEX IX_BILRG_OrderOp_OrderDate
    ON BILRG_OrderOp (OrderDate, OrderOpId)
    WITH(FILLFACTOR=98)
GO
