CREATE TABLE BILRG_RoomCat 
(
    RoomCatId VARCHAR(3) NOT NULL CONSTRAINT DF_BILRG_RoomCat_RoomCatId DEFAULT(''),
    RoomCatName VARCHAR(25) NOT NULL CONSTRAINT DF_BILRG_RoomCat_RoomCatName DEFAULT(''),
    
    CONSTRAINT PK_BILRG_RoomCat_RoomCatId PRIMARY KEY CLUSTERED (RoomCatID)
)