<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AdmisiContext\JaminanFeature\PolisAgg\**" />
    <EmbeddedResource Remove="AdmisiContext\JaminanFeature\PolisAgg\**" />
    <None Remove="AdmisiContext\JaminanFeature\PolisAgg\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpDal.cs" />
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpDto.cs" />
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpPpaDto.cs" />
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpRepo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Moq" Version="4.20.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bilreg.Application\Bilreg.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\" />
  </ItemGroup>

</Project>
