INSERT INTO T_REK_TIPE (FS_KD_REK_TIPE, FS_NM_REK_TIPE, FB_NERACA, FN_URUT, FS_DK) 
VALUES
('AKM DPS', 'Akumulasi Depresiasi', 1, 13, 'K'),
('AKTV LAIN', 'Aktiva Lain - Lain', 1, 14, 'D'),
('AKTV LCR', 'Aktiva Lancar', 1, 8, 'D'),
('AKTV TETAP', 'Aktiva Tetap', 1, 12, 'D'),
('BELI', 'Pembelian', 0, 27, 'D'),
('BELI DISC', 'Potongan Pembelian', 0, 28, 'K'),
('BELI RETUR', 'Retur Pembelian', 0, 29, 'K'),
('BY ADM', 'Biaya Administrasi & Umum', 0, 33, 'D'),
('BY BELI', 'Biaya Pembelian', 0, 30, 'D'),
('BY BUNGA', 'Biaya Bunga', 0, 38, 'D'),
('BY JUAL', 'Biaya Penjualan', 0, 31, 'D'),
('BY LAIN', 'Biaya Luar Usaha', 0, 35, 'D'),
('BY PAJAK', 'Biaya Pajak', 0, 39, 'D'),
('BY USAHA', 'Biaya Usaha', 0, 32, 'D'),
('EKUITAS', 'Ekuitas', 1, 20, 'K'),
('GR KELUAR', 'Giro Keluar', 1, 17, 'K'),
('GR MASUK', 'Giro Masuk', 1, 5, 'D'),
('HPP', 'HPP', 0, 26, 'D'),
('HT LAIN L', 'Hutang Lain Lancar', 1, 16, 'K'),
('HT LAIN P', 'Hutang Lain Jangka Panjang', 1, 19, 'K'),
('HT USAHA L', 'Hutang Usaha Lancar', 1, 15, 'K'),
('HT USAHA P', 'Hutang Usaha Jangka Panjang', 1, 18, 'K'),
('INV L', 'Investasi Jangka Pendek', 1, 3, 'D'),
('INV P', 'Investasi Jangka Panjang', 1, 11, 'D'),
('JUAL DISC', 'Potongan Penjualan', 0, 24, 'D'),
('JUAL RETUR', 'Retur Penjualan', 0, 25, 'D'),
('KAS', 'Kas', 1, 1, 'D'),
('KAS BANK', 'Kas Bank', 1, 2, 'D'),
('LABA JALAN', 'Laba Bulan Berjalan', 1, 22, 'K'),
('LABA TAHAN', 'Laba Ditahan', 1, 21, 'K'),
('PDPT LAIN', 'Pendapatan Luar Usaha', 0, 34, 'K'),
('PDPT USAHA', 'Pendapatan Usaha', 0, 23, 'K'),
('PERSEDIAAN', 'Persediaan', 1, 7, 'D'),
('PJK KELUAR', 'Pajak Keluaran', 1, 37, 'D'),
('PJK MASUK', 'Pajak Masukan', 1, 36, 'K'),
('PT LAIN L', 'Piutang Lain - Lain Lancar', 1, 6, 'D'),
('PT LAIN P', 'Piutang Lain Jangka Panjang', 1, 10, 'D'),
('PT USAHA L', 'Piutang Usaha Lancar', 1, 4, 'D'),
('PT USAHA P', 'Piutang Usaha Jangka Panjang', 1, 9, 'D');