CREATE TABLE T_REK_TIPE (
    FS_KD_REK_TIPE VARCHAR(10) NOT NULL CONSTRAINT DF_T_REK_TIPE_FS_KD_REK_TIPE DEFAULT(''),
    FS_NM_REK_TIPE VARCHAR(30) NOT NULL CONSTRAINT DF_T_REK_TIPE_FS_NM_REK_TIPE DEFAULT(''),
    FB_NERACA BIT NOT NULL CONSTRAINT DF_T_REK_TIPE_FB_NERACA DEFAULT(0),
    FN_URUT DECIMAL(20, 0) NOT NULL CONSTRAINT DF_T_REK_TIPE_FN_URUT DEFAULT 0,
    FS_DK VARCHAR(12) NOT NULL CONSTRAINT DF_T_REK_TIPE_FS_DK DEFAULT(''),
    
    CONSTRAINT PK_T_REK_TIPE PRIMARY KEY (FS_KD_REK_TIPE)
);
