CREATE TABLE BILRG_IgdVisit (
    IgdVisitId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_IgdVisitId DEFAULT(''),
    DaftarDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_DaftarDateTime DEFAULT('3000-01-01'),

    VisitorName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VisitorName DEFAULT(''),
    VisitorGender VARCHAR(1) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VisitorGender DEFAULT(''),
    VisitorTglLahir DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VisitorTglLahir DEFAULT('3000-01-01'),
    VisitorKontak VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VisitorKontak DEFAULT(''),

    DokterId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_DokterId DEFAULT(''),
    DokterName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_DokterName DEFAULT(''),

    HasTriage BIT NOT NULL CONSTRAINT DF_BILRG_IgdVisit_HasTriage DEFAULT(0),
    TriageMethod VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_TriageMethod DEFAULT(''),
    TriageLevel VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_TriageLevel DEFAULT(''),
    TriageColor VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_TriageColor DEFAULT(''),
    LastTriageAt DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_LastTriageAt DEFAULT('3000-01-01'),
    NextReTriageAt DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_NextReTriageAt DEFAULT('3000-01-01'),

    AdministrativeState VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_AdministrativeState DEFAULT('DAFTAR'),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_RegId DEFAULT(''),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_PasienId DEFAULT(''),
    PasienName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_PasienName DEFAULT(''),

    RedirectRajalId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_RedirectRajalId DEFAULT(''),
    RedirectDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_RedirectDateTime DEFAULT('3000-01-01'),
    RedirectReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_RedirectReason DEFAULT(''),

    BedIgdId VARCHAR(8) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_BedIgdId DEFAULT(''),

    DischargeUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_DischargeUser DEFAULT(''),
    DischargeDateTime DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_DischargeDateTime DEFAULT('3000-01-01'),

    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_IgdVisit_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_IgdVisit PRIMARY KEY CLUSTERED (IgdVisitId)
);
GO

CREATE INDEX IX_BILRG_IgdVisit_State ON BILRG_IgdVisit(AdministrativeState, VodDate);
GO
CREATE INDEX IX_BILRG_IgdVisit_BedIgd ON BILRG_IgdVisit(BedIgdId) WHERE BedIgdId <> '';
GO
CREATE INDEX IX_BILRG_IgdVisit_Reg ON BILRG_IgdVisit(RegId) WHERE RegId <> '';
GO
CREATE INDEX IX_BILRG_IgdVisit_NextReTriageAt ON BILRG_IgdVisit(NextReTriageAt);
GO
