CREATE TABLE TA_LAYANAN_DK (
        FS_KD_LAYANAN_DK VARCHAR(3) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FS_KD_LAYANAN_DK DEFAULT(''),
        FS_NM_LAYANAN_DK VARCHAR(30) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FS_NM_LAYANAN_DK DEFAULT(''),
        FN_RAWAT_INAP DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_RAWAT_INAP DEFAULT 0,
        FN_RAWAT_JALAN DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_RAWAT_JALAN DEFAULT 0,
        FN_KESEHATAN_JIWA DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_KESEHATAN_JIWA DEFAULT 0,
        FN_BEDAH DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_BEDAH DEFAULT 0,
        FN_RUJUKAN DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_RUJUKAN DEFAULT 0,
        FN_KUNJ_RUMAH DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_KUNJ_RUMAH DEFAULT 0,
        FN_LAYANAN_SUB DECIMAL(20, 0) NOT NULL CONSTRAINT DF_TA_LAYANAN_DK_FN_LAYANAN_SUB DEFAULT 0
    
    CONSTRAINT PK_TA_LAYANAN_DK PRIMARY KEY (FS_KD_LAYANAN_DK)
);