<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ChargeContext\TindakanFeature\TipeTarifAgg\**" />
    <EmbeddedResource Remove="ChargeContext\TindakanFeature\TipeTarifAgg\**" />
    <None Remove="ChargeContext\TindakanFeature\TipeTarifAgg\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BedUsageContext\KamarOperasiFeature\StartOpModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="Nuna.Lib.NetStandard" Version="3.4.156" />
    <PackageReference Include="Ulid" Version="1.3.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BedUsageContext\HousekeepingFeature\" />
    <Folder Include="BedUsageContext\PakaiBedFeature\" />
    <Folder Include="Shared\" />
  </ItemGroup>

</Project>
