INSERT INTO ta_rujukan_tipe (fs_kd_rujukan_tipe, fs_nm_rujukan_tipe)
SELECT '1', 'DATANG SENDIRI' UNION
SELECT '2', 'BIDES' UNION
SELECT '3', 'DR / BIDAN' UNION
SELECT '4', 'PUSKESMAS' UNION
SELECT '5', 'INSTALASI LAIN' UNION
SELECT '6', 'RS PEMERINTAH' UNION
SELECT '7', 'RS SWASTA' UNION
SELECT '8', 'DATANG MENINGGAL'
