CREATE TABLE BILRG_RegAktif(
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_RegId DEFAULT(''),
    RegDate Datetime NOT NULL CONSTRAINT DF_BILRG_RegDate DEFAULT('3000-01-01'),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_Pasien DEFAULT(''),
    JenisReg VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_JenisReg DEFAULT(''),
    LayananId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_LayananId DEFAULT(''),
    DokterId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_DokterId DEFAULT(''),
    TipeJaminanId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_TipeJaminanId DEFAULT(''),
    
    CONSTRAINT PK_BILRG_RegAktif PRIMARY KEY CLUSTERED(RegId)
)