CREATE TABLE BILRG_LabOrderItem
(
    OrderId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_OrderId DEFAULT(''),
    ItemNo INT NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_ItemNo DEFAULT(0),

    TestId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TestId DEFAULT(''),
    TestCode VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TestCode DEFAULT(''),
    TestName VARCHAR(100) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TestName DEFAULT(''),

    TarifId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TarifId DEFAULT(''),
    TarifCode VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TarifCode DEFAULT(''),
    TarifName VARCHAR(100) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TarifName DEFAULT(''),

    TubeType INT NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_TubeType DEFAULT(0),
    SpecimenType VARCHAR(30) NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_SpecimenType DEFAULT(''),
    RequiredTubeCount INT NOT NULL CONSTRAINT DF_BILRG_LabOrderItem_RequiredTubeCount DEFAULT(0),

    CONSTRAINT PK_BILRG_LabOrderItem PRIMARY KEY CLUSTERED (OrderId, ItemNo)
)
GO
