CREATE TABLE BILRG_LabOrder (
    OrderId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_LabOrder_OrderId DEFAULT(''),
    OrderNo VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_LabOrder_OrderNo DEFAULT(''),
    OrderSource INT NOT NULL CONSTRAINT DF_BILRG_LabOrder_OrderSource DEFAULT(0),
    LabOrderStatus INT NOT NULL CONSTRAINT DF_BILRG_LabOrder_LabOrderStatus DEFAULT(0),
    OwareStatus INT NOT NULL CONSTRAINT DF_BILRG_LabOrder_OwareStatus DEFAULT(0),

    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_LabOrder_RegId DEFAULT(''),
    PatientId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_LabOrder_PatientId DEFAULT(''),
    PatientName VARCHAR(60) NOT NULL CONSTRAINT DF_BILRG_LabOrder_PatientName DEFAULT(''),
    BirthDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_BirthDate DEFAULT('3000-01-01'),
    Gender VARCHAR(1) NOT NULL CONSTRAINT DF_BILRG_LabOrder_Gender DEFAULT(''),
    AgeAtOrder INT NOT NULL CONSTRAINT DF_BILRG_LabOrder_AgeAtOrder DEFAULT(0),

    ExecutionRegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_LabOrder_ExecutionRegId DEFAULT(''),
    DeferredReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_DeferredReason DEFAULT(''),
    DeferredUntil DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_DeferredUntil DEFAULT('3000-01-01'),
    BillingTindakanId VARCHAR(12) NOT NULL CONSTRAINT DF_BILRG_LabOrder_BillingTindakanId DEFAULT(''),
    BillingLastError VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_BillingLastError DEFAULT(''),

    CollectedDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_CollectedDate DEFAULT('3000-01-01'),
    CollectedUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_CollectedUserId DEFAULT(''),
    CollectionNote VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_CollectionNote DEFAULT(''),

    ReleasedDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_ReleasedDate DEFAULT('3000-01-01'),
    ReleasedUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_ReleasedUserId DEFAULT(''),
    ReleaseNote VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_ReleaseNote DEFAULT(''),

    CancelledReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_CancelledReason DEFAULT(''),
    CancelledDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_CancelledDate DEFAULT('3000-01-01'),
    CancelledUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_CancelledUserId DEFAULT(''),
    TerminationReason VARCHAR(200) NOT NULL CONSTRAINT DF_BILRG_LabOrder_TerminationReason DEFAULT(''),
    TerminationDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_TerminationDate DEFAULT('3000-01-01'),
    TerminationUserId VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_TerminationUserId DEFAULT(''),

    CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_CrtUser DEFAULT(''),
    CrtDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_CrtDate DEFAULT('3000-01-01'),
    UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_UpdUser DEFAULT(''),
    UpdDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_UpdDate DEFAULT('3000-01-01'),
    VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_LabOrder_VodUser DEFAULT(''),
    VodDate DATETIME NOT NULL CONSTRAINT DF_BILRG_LabOrder_VodDate DEFAULT('3000-01-01'),

    CONSTRAINT PK_BILRG_LabOrder PRIMARY KEY CLUSTERED (OrderId)
);
GO

CREATE INDEX IX_BILRG_LabOrder_Status ON BILRG_LabOrder(LabOrderStatus, CrtDate);
GO
CREATE INDEX IX_BILRG_LabOrder_Reg ON BILRG_LabOrder(RegId, LabOrderStatus) WHERE RegId <> '';
GO
CREATE INDEX IX_BILRG_LabOrder_OrderNo ON BILRG_LabOrder(OrderNo);
GO
