CREATE TABLE BILRG_PasienTracker(
	TrackerId VARCHAR(16) NOT NULL CONSTRAINT DF_BILRG_PasienTracker_TrackerId DEFAULT(''),
	VisitorName VARCHAR(64) NOT NULL CONSTRAINT DF_BILRG_PasienTracker_VisitorName DEFAULT(''),
	TglLahir DATETIME NOT NULL CONSTRAINT DF_BILRG_PasienTracker_TglLahir DEFAULT(''),
	VisitDate DATETIME NOT NULL CONSTRAINT DF_BILRG_PasienTracker_VisitDate DEFAULT(''),
	RegId VARCHAR(10) NOT NULL CONSTRAINT DF_BILRG_PasienTracker_RegId DEFAULT(''),
	
	CONSTRAINT PK_BILRG_PasienTracker_TrackerId PRIMARY KEY CLUSTERED(TrackerId)
)