CREATE TABLE BILRG_PasienTracker(
    PasienTrackerId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_PasienTracker_PasienTrackerId DEFAULT(''),
    PersonName VARCHAR(50) NOT NULL CONSTRAINT DF_BILRG_PasienTracker_PersonName DEFAULT(''),
    TglLahir DATETIME NOT NULL CONSTRAINT DF_BILRG_PasienTracker_TglLahir DEFAULT('3000-01-01'),
    VisitDate DATETIME NOT NULL CONSTRAINT DF_BILRG_PasienTracker_VisitDate DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_BILRG_PasienTracker PRIMARY KEY CLUSTERED (PasienTrackerId)
)