CREATE TABLE BILRG_AntrianEntry(
    AntrianId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_AntrianId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_NoUrut DEFAULT(0),
    PersonName VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_PersonName DEFAULT(''),
    PasienTrackerId VARCHAR(26) NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_PasienTrackerId DEFAULT(''),
    AntrianStatus INT NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_AntrianStatus DEFAULT(0),
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_CreatedAt DEFAULT('3000-01-01'),
    ServedAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_ServedAt DEFAULT('3000-01-01'),
    DoneAt DATETIME NOT NULL CONSTRAINT DF_BILRG_AntrianEntry_DoneAt DEFAULT('3000-01-01')
    
    CONSTRAINT PK_BILRG_AntrianEntry PRIMARY KEY CLUSTERED (AntrianId, NoUrut)    
)