<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Taksaka.Abstractions\Taksaka.Abstractions.csproj" />
    <ProjectReference Include="..\Taksaka.Core\Taksaka.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Taksaka.Workers.Integration.plugin.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
