CREATE TABLE BILRG_Pasien(
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_BILRG_Pasien_PasienId DEFAULT(''),
    
    AlamatKtp1 VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_Pasien_AlamatKtp1 DEFAULT(''),
    AlamatKtp2 VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_Pasien_AlamatKtp2 DEFAULT(''),
    AlamatKtp3 VARCHAR(40) NOT NULL CONSTRAINT DF_BILRG_Pasien_AlamatKtp3 DEFAULT(''),
    AlamatKtpKota VARCHAR(20) NOT NULL CONSTRAINT DF_BILRG_Pasien_AlamatKtpKota DEFAULT(''),
    AlamatKtpKodePos VARCHAR(6) NOT NULL CONSTRAINT DF_BILRG_Pasien_AlamatKtpKodePos DEFAULT(''),
    
    CONSTRAINT PK_BILRG_Pasien PRIMARY KEY CLUSTERED(PasienId)
)